# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\Python\ImuEduStudio\app\views\templates\control_rotation_stand_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlRotationStand(object):
    def setupUi(self, ControlRotationStand):
        ControlRotationStand.setObjectName("ControlRotationStand")
        ControlRotationStand.resize(270, 182)
        ControlRotationStand.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(67, 67, 67);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ControlRotationStand)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(ControlRotationStand)
        self.widget.setMinimumSize(QtCore.QSize(0, 139))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.bt_rotator_send = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bt_rotator_send.setFont(font)
        self.bt_rotator_send.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(70, 70, 70) ;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(74, 74, 74);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgb(54, 54, 54) ;\n"
"    background-color: rgb(20, 20, 20);\n"
"}")
        self.bt_rotator_send.setObjectName("bt_rotator_send")
        self.gridLayout.addWidget(self.bt_rotator_send, 4, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 1)
        self.lb_rotator_status = QtWidgets.QLabel(self.widget)
        self.lb_rotator_status.setObjectName("lb_rotator_status")
        self.gridLayout.addWidget(self.lb_rotator_status, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.rb_send_angle = QtWidgets.QRadioButton(self.widget)
        self.rb_send_angle.setMinimumSize(QtCore.QSize(20, 0))
        self.rb_send_angle.setText("")
        self.rb_send_angle.setObjectName("rb_send_angle")
        self.gridLayout.addWidget(self.rb_send_angle, 1, 1, 1, 1)
        self.rb_send_rotation = QtWidgets.QRadioButton(self.widget)
        self.rb_send_rotation.setMinimumSize(QtCore.QSize(20, 0))
        self.rb_send_rotation.setMaximumSize(QtCore.QSize(20, 16777215))
        self.rb_send_rotation.setText("")
        self.rb_send_rotation.setChecked(True)
        self.rb_send_rotation.setObjectName("rb_send_rotation")
        self.gridLayout.addWidget(self.rb_send_rotation, 2, 1, 1, 1)
        self.sb_rotator_angle = QtWidgets.QSpinBox(self.widget)
        self.sb_rotator_angle.setMaximum(359)
        self.sb_rotator_angle.setObjectName("sb_rotator_angle")
        self.gridLayout.addWidget(self.sb_rotator_angle, 1, 2, 1, 2)
        self.sb_rotator_rotation = QtWidgets.QSpinBox(self.widget)
        self.sb_rotator_rotation.setObjectName("sb_rotator_rotation")
        self.gridLayout.addWidget(self.sb_rotator_rotation, 2, 2, 1, 2)
        self.sb_rotator_speed = QtWidgets.QSpinBox(self.widget)
        self.sb_rotator_speed.setMaximum(1500)
        self.sb_rotator_speed.setObjectName("sb_rotator_speed")
        self.gridLayout.addWidget(self.sb_rotator_speed, 3, 2, 1, 2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ControlRotationStand)
        QtCore.QMetaObject.connectSlotsByName(ControlRotationStand)

    def retranslateUi(self, ControlRotationStand):
        _translate = QtCore.QCoreApplication.translate
        ControlRotationStand.setWindowTitle(_translate("ControlRotationStand", "Form"))
        self.label_11.setText(_translate("ControlRotationStand", "Статус стенду:"))
        self.bt_rotator_send.setText(_translate("ControlRotationStand", "Надіслати"))
        self.label_12.setText(_translate("ControlRotationStand", "Кут:"))
        self.label_14.setText(_translate("ControlRotationStand", "Швидкість (крок/с):"))
        self.lb_rotator_status.setText(_translate("ControlRotationStand", "Не підключено"))
        self.label_13.setText(_translate("ControlRotationStand", "Оберти:"))
