# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\ImuEdu\app\views\templates\simple_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimpleView(object):
    def setupUi(self, SimpleView):
        SimpleView.setObjectName("SimpleView")
        SimpleView.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimpleView.setWindowIcon(icon)
        self.bt_1 = QtWidgets.QPushButton(SimpleView)
        self.bt_1.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.bt_1.setObjectName("bt_1")

        self.retranslateUi(SimpleView)
        QtCore.QMetaObject.connectSlotsByName(SimpleView)

    def retranslateUi(self, SimpleView):
        _translate = QtCore.QCoreApplication.translate
        SimpleView.setWindowTitle(_translate("SimpleView", "SimpleView"))
        self.bt_1.setText(_translate("SimpleView", "PushButton"))
from app.views import resources_rc
